---
name: Lint

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: jhollowe-addons/workflows/.github/workflows/repository-lint.yaml@main
